# Generated by Django 3.0.5 on 2020-11-27 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mozip1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview_group',
            name='fixed',
            field=models.BooleanField(default=False),
        ),
    ]
