# Generated by Django 3.0.5 on 2020-11-27 05:38

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mozip1', '0002_interview_group_fixed'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewPostimeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rf_id', models.CharField(max_length=15)),
                ('interviewees', djongo.models.fields.JSONField()),
                ('interviewers', djongo.models.fields.JSONField()),
                ('times', djongo.models.fields.JSONField()),
            ],
        ),
    ]
