# Generated by Django 3.0.5 on 2020-11-24 11:55

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mozip1', '0002_auto_20201124_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='interview_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rf_id', models.CharField(default=None, max_length=15)),
                ('interviewer', djongo.models.fields.JSONField()),
                ('manager', djongo.models.fields.JSONField()),
                ('etc', djongo.models.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='interview_manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_time', models.PositiveIntegerField(default=0)),
                ('rest_time', models.PositiveIntegerField(default=0)),
                ('rf_id', models.CharField(default=None, max_length=15)),
                ('manager', djongo.models.fields.JSONField()),
            ],
        ),
       
    ]
