# Generated by Django 3.1.1 on 2020-09-26 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mozip1', '0002_auto_20200926_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='project',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
