# Generated by Django 3.0.5 on 2020-11-27 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mozip1', '0003_interviewpostimemodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InterviewPostimeModel',
            new_name='Interview_Postime',
        ),
    ]
