# Generated by Django 3.0.5 on 2020-11-14 07:32

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mozip1', '0004_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('group', models.CharField(choices=[('g1', '학생'), ('g2', '직장인'), ('g3', '일반인')], default='g1', max_length=3)),
                ('name', models.CharField(max_length=15)),
                ('education', djongo.models.fields.JSONField()),
                ('grader', models.CharField(choices=[('gr1', '1학년'), ('gr2', '2학년'), ('gr3', '3학년'), ('gr4', '4학년')], default='gr1', max_length=4)),
                ('states', models.CharField(choices=[('s1', '재학'), ('s2', '휴학'), ('s3', '졸업')], default='s1', max_length=3)),
                ('birthday', models.CharField(max_length=12)),
                ('telephone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', djongo.models.fields.JSONField()),
                ('self_image', models.CharField(max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('user_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
