# Generated by Django 3.0.5 on 2020-11-19 15:10

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mozip1', '0005_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club_FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FAQ', djongo.models.fields.JSONField()),
                ('club_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Club_introduce',
            fields=[
                ('title', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=5)),
                ('region', djongo.models.fields.JSONField()),
                ('target', models.CharField(choices=[('t1', '대학생'), ('t2', '직장인'), ('t3', '일반인')], default='t1', max_length=10)),
                ('time', models.CharField(max_length=10)),
                ('mainURL', models.URLField()),
                ('detail', djongo.models.fields.JSONField()),
                ('poster', models.CharField(max_length=5)),
                ('card_image', djongo.models.fields.JSONField()),
                ('club_id', models.IntegerField()),
                ('ci_id', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Club_member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', djongo.models.fields.JSONField()),
                ('club_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Club_review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', djongo.models.fields.JSONField()),
                ('club_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Creation_Club',
            fields=[
                ('cc_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=15)),
                ('information', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('c1', '학술'), ('c2', '예술'), ('c3', '친목'), ('c4', '스포츠'), ('c5', '여행'), ('c6', '종교'), ('c7', '봉사'), ('c8', '기타')], default='c1', max_length=8)),
                ('foundationdate', djongo.models.fields.JSONField()),
                ('detail_information', models.TextField(max_length=300)),
                ('self_image', models.CharField(max_length=10)),
                ('telephone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('approval', models.CharField(choices=[('a1', '미확인'), ('a2', '승인'), ('a3', '승인불가')], default='a1', max_length=8)),
                ('created_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pass_Fail',
            fields=[
                ('Type', models.CharField(choices=[('1', '면접전형'), ('2', '서류전형'), ('3', '면접+서류전형')], default='1', max_length=15)),
                ('ci_id', models.CharField(max_length=15)),
                ('user_id', models.PositiveIntegerField()),
                ('pass_fail', models.CharField(choices=[('1', '합격'), ('2', '불합격'), ('3', '보류'), ('4', '미결정')], default='1', max_length=10)),
                ('detail', djongo.models.fields.JSONField()),
                ('pf_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='recruit_basic_question',
            fields=[
                ('number', models.PositiveIntegerField()),
                ('basic', djongo.models.fields.JSONField()),
                ('optional', djongo.models.fields.JSONField()),
                ('club_id', models.IntegerField()),
                ('user_id', models.PositiveIntegerField()),
                ('rbq_id', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='recruit_format',
            fields=[
                ('number', models.PositiveIntegerField()),
                ('Type', models.CharField(choices=[('1', '면접전형'), ('2', '서류전형'), ('3', '면접+서류전형')], default='1', max_length=15)),
                ('club_id', models.IntegerField()),
                ('user_id', models.PositiveIntegerField()),
                ('document', djongo.models.fields.JSONField()),
                ('rf_id', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='recruit_notice',
            fields=[
                ('notice', djongo.models.fields.JSONField()),
                ('ci_id', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='recruit_QA',
            fields=[
                ('QA', djongo.models.fields.JSONField()),
                ('ci_id', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_apply_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('apply_list', djongo.models.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='user_circle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('states', models.CharField(choices=[('1', '모집안함'), ('2', '모집중'), ('3', '서류 진행'), ('4', '면접 진행'), ('5', '회비 입금 대기 중')], default='1', max_length=15)),
                ('club_in', djongo.models.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='user_recordQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('recordQ', djongo.models.fields.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.RemoveField(
            model_name='club',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='club',
            name='id',
        ),
        migrations.RemoveField(
            model_name='club',
            name='project',
        ),
        migrations.AddField(
            model_name='club',
            name='card_image',
            field=djongo.models.fields.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='club',
            name='cc_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='club',
            name='detail_information',
            field=models.TextField(default=None, max_length=300),
        ),
        migrations.AddField(
            model_name='club',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='club',
            name='foundationdate',
            field=djongo.models.fields.JSONField(default=None),
        ),
        migrations.AddField(
            model_name='club',
            name='information',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='self_image',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='club',
            name='telephone',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='club',
            name='category',
            field=models.CharField(choices=[('c1', '학술'), ('c2', '예술'), ('c3', '친목'), ('c4', '스포츠'), ('c5', '여행'), ('c6', '종교'), ('c7', '봉사'), ('c8', '기타')], default='c1', max_length=8),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
